//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.15 at 07:33:52 PM GMT-05:00 
//


package trng.imcs.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Address complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Address"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Adressline" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="City" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ZipCode" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="AdressType"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="HOME"/&gt;
 *               &lt;enumeration value="COMMUNICATION"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Address", propOrder = {
    "adressline",
    "city",
    "zipCode",
    "adressType"
})
public class Address {

    @XmlElement(name = "Adressline", required = true)
    protected String adressline;
    @XmlElement(name = "City", required = true)
    protected String city;
    @XmlElement(name = "ZipCode")
    protected double zipCode;
    @XmlElement(name = "AdressType", required = true)
    protected String adressType;

    
    
    @Override
	public String toString() {
		return "Address [adressline=" + adressline + ", city=" + city + ", zipCode=" + zipCode + ", adressType="
				+ adressType + "]";
	}

	/**
     * Gets the value of the adressline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdressline() {
        return adressline;
    }

    /**
     * Sets the value of the adressline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdressline(String value) {
        this.adressline = value;
    }

    /**
     * Gets the value of the city property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCity() {
        return city;
    }

    /**
     * Sets the value of the city property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCity(String value) {
        this.city = value;
    }

    /**
     * Gets the value of the zipCode property.
     * 
     */
    public double getZipCode() {
        return zipCode;
    }

    /**
     * Sets the value of the zipCode property.
     * 
     */
    public void setZipCode(double value) {
        this.zipCode = value;
    }

    /**
     * Gets the value of the adressType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdressType() {
        return adressType;
    }

    /**
     * Sets the value of the adressType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdressType(String value) {
        this.adressType = value;
    }

}
